liste = [17, 38, 10, 25, 72]
liste.sort()
print(liste)
liste.append(12)
print(liste)
liste.reverse()
print(liste)
i17=liste.index(17)
print(i17)
liste.remove(38)
print(liste)
print(liste[:2])
print(liste[2:])
print(liste[-1])